[package]
name = "rawcover_collector"
version = "0.0.1"
authors = ["samhaosss <sunhaoyl@outlook.com>"]
edition = "2018"

[dependencies]
url="*"
reqwest="*"
clap="*"
chrono="*"
ctrlc = "*"
log="*"
simplelog="*"
select = "*"
exitcode = "*"